name: Testing the runner
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'
env:
  HARBOR_IMAGE_NAME: testing-image
  VERSION: latest

jobs:
  build-docker-image:
    runs-on: runner-scale-set
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.HARBOR_IMAGE_NAME }}:${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Last step to check
        run: echo "🎉 This job uses runner scale set runners!"
